# Generated by Django 5.1.7 on 2025-03-10 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='is_team_admin',
            field=models.BooleanField(default=False, help_text='Designates whether this member can manage team members'),
        ),
    ]
