# Generated by Django 5.1.7 on 2025-03-10 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_alter_teammember_unique_together_teammember_email_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teammember',
            unique_together={('team', 'email'), ('team', 'user')},
        ),
    ]
