# Generated by Django 5.1.7 on 2025-03-10 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pics/castolo.png', null=True, upload_to='profile_pics/'),
        ),
    ]
