# Generated by Django 5.1.7 on 2025-03-10 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('GK', 'Goalkeeper'), ('SW', 'Sweeper'), ('CB', 'Center Back'), ('LB', 'Left Back'), ('RB', 'Right Back'), ('LWB', 'Left Wing Back'), ('RWB', 'Right Wing Back'), ('DM', 'Defensive Midfielder'), ('CM', 'Central Midfielder'), ('WM', 'Wing Midfielder'), ('LM', 'Left Midfielder'), ('RM', 'Right Midfielder'), ('AM', 'Attacking Midfielder'), ('LW', 'Left Winger'), ('RW', 'Right Winger'), ('SS', 'Second Striker'), ('CF', 'Center Forward'), ('ST', 'Striker'), ('LF', 'Left Forward'), ('RF', 'Right Forward')], max_length=3, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('GK', 'Goalkeeper'), ('DEF', 'Defense'), ('MID', 'Midfield'), ('ATT', 'Attack')], max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='player_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='profile_pics/castolo.png', upload_to='profile_pics/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teams.position'),
        ),
    ]
