# Generated by Django 5.1.7 on 2025-03-10 19:43

from django.db import migrations

def create_initial_positions(apps, schema_editor):
    Position = apps.get_model('teams', 'Position')
    
    positions = [
        # Goalkeeper
        {'code': 'GK', 'name': 'Goalkeeper', 'type': 'GK'},
        # Defense
        {'code': 'SW', 'name': 'Sweeper', 'type': 'DEF'},
        {'code': 'CB', 'name': 'Center Back', 'type': 'DEF'},
        {'code': 'LB', 'name': 'Left Back', 'type': 'DEF'},
        {'code': 'RB', 'name': 'Right Back', 'type': 'DEF'},
        {'code': 'LWB', 'name': 'Left Wing Back', 'type': 'DEF'},
        {'code': 'RWB', 'name': 'Right Wing Back', 'type': 'DEF'},
        # Midfield
        {'code': 'DM', 'name': 'Defensive Midfielder', 'type': 'MID'},
        {'code': 'CM', 'name': 'Central Midfielder', 'type': 'MID'},
        {'code': 'WM', 'name': 'Wing Midfielder', 'type': 'MID'},
        {'code': 'LM', 'name': 'Left Midfielder', 'type': 'MID'},
        {'code': 'RM', 'name': 'Right Midfielder', 'type': 'MID'},
        {'code': 'AM', 'name': 'Attacking Midfielder', 'type': 'MID'},
        # Attack
        {'code': 'LW', 'name': 'Left Winger', 'type': 'ATT'},
        {'code': 'RW', 'name': 'Right Winger', 'type': 'ATT'},
        {'code': 'SS', 'name': 'Second Striker', 'type': 'ATT'},
        {'code': 'CF', 'name': 'Center Forward', 'type': 'ATT'},
        {'code': 'ST', 'name': 'Striker', 'type': 'ATT'},
        {'code': 'LF', 'name': 'Left Forward', 'type': 'ATT'},
        {'code': 'RF', 'name': 'Right Forward', 'type': 'ATT'},
    ]
    
    for position_data in positions:
        Position.objects.create(**position_data)

def remove_initial_positions(apps, schema_editor):
    Position = apps.get_model('teams', 'Position')
    Position.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_position_profile_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RunPython(create_initial_positions, remove_initial_positions),
    ]
