# Generated by Django 5.1.7 on 2025-03-10 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0010_season_match'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='location',
        ),
        migrations.RemoveField(
            model_name='match',
            name='status',
        ),
        migrations.AddField(
            model_name='match',
            name='field_number',
            field=models.PositiveIntegerField(default=1, help_text='Enter the field number'),
            preserve_default=False,
        ),
    ]
