# Generated by Django 5.1.7 on 2025-03-10 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0011_remove_match_location_remove_match_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_official',
            field=models.BooleanField(default=False, help_text='Indicates if the player is officially registered'),
        ),
    ]
