# Generated by Django 5.1.7 on 2025-03-11 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0013_profile_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pics/castolo.png', upload_to='profile_pics/'),
        ),
    ]
