# Generated by Django 5.1.7 on 2025-03-11 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0015_payment_playerpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerpayment',
            name='admin_verified',
            field=models.BooleanField(default=False),
        ),
    ]
