# Generated by Django 5.1.7 on 2025-03-12 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0016_playerpayment_admin_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(choices=[('CL', 'Chile'), ('AR', 'Argentina'), ('BO', 'Bolivia'), ('BR', 'Brazil'), ('CO', 'Colombia'), ('EC', 'Ecuador'), ('PE', 'Peru'), ('PY', 'Paraguay'), ('UY', 'Uruguay'), ('VE', 'Venezuela'), ('DE', 'Germany'), ('ES', 'Spain'), ('FR', 'France'), ('GB', 'United Kingdom'), ('IT', 'Italy'), ('MX', 'Mexico'), ('NL', 'Netherlands'), ('PT', 'Portugal'), ('US', 'United States')], default='CL', help_text="Player's country", max_length=2),
        ),
    ]
