# Generated by Django 5.1.7 on 2025-03-12 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0020_alter_team_team_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.CharField(blank=True, help_text='A short description (max 20 characters)', max_length=20),
        ),
    ]
