# Generated by Django 5.1.7 on 2025-03-12 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0021_profile_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='condition',
            field=models.CharField(choices=[('TOP', 'Top Condition'), ('GOOD', 'Good Condition'), ('NORMAL', 'Normal Condition'), ('BAD', 'Bad Condition'), ('AWFUL', 'Awful Condition')], default='NORMAL', help_text="Player's current condition", max_length=10),
        ),
    ]
