# Generated by Django 5.1.7 on 2025-03-12 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0022_profile_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='active_player',
            field=models.BooleanField(default=True, help_text='Indicates if the player is currently active'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='condition',
            field=models.CharField(choices=[('TOP', 'Top Condition'), ('GOOD', 'Good Condition'), ('NORMAL', 'Normal Condition'), ('BAD', 'Bad Condition'), ('AWFUL', 'Awful Condition'), ('INJURED', 'Injured')], default='NORMAL', help_text="Player's current condition", max_length=10),
        ),
    ]
