# Generated by Django 5.1.7 on 2025-03-13 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0024_playermatchstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='away_score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='home_score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
