# Generated by Django 5.1.7 on 2025-03-14 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0025_match_away_score_match_home_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='playermatchstats',
            name='assists',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
