# Generated by Django 5.1.7 on 2025-03-19 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0028_remove_team_specific_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='active_player',
            field=models.BooleanField(default=True, help_text='Whether this member is an active player'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='is_official',
            field=models.BooleanField(default=False, help_text='Whether this member is an official player'),
        ),
    ]
