# Generated by Django 5.1.7 on 2025-03-23 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0028_add_match_official_mvp'),
        ('teams', '0029_teammember_active_player_teammember_is_official'),
    ]

    operations = [
    ]
