# Generated by Django 5.1.7 on 2025-03-23 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0030_merge_20250323_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='slach_account',
            field=models.CharField(blank=True, help_text="Slach account for payment link (e.g. 'lpcfc')", max_length=50, null=True),
        ),
    ]
