# Generated by Django 5.1.7 on 2025-03-23 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0031_add_slach_account_to_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='slach_account',
        ),
        migrations.AddField(
            model_name='season',
            name='slach_account',
            field=models.CharField(blank=True, help_text="Slach account for payment links (e.g. 'lpcfc')", max_length=50, null=True),
        ),
    ]
