# Generated by Django 5.1.7 on 2025-04-02 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0033_alter_match_field_number_alter_match_match_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_photo',
            field=models.ImageField(blank=True, default='https://lpc-static-files-2024.s3.amazonaws.com/media/team_photos/default.png', help_text='Upload a square team photo', upload_to='team_photos/'),
        ),
        migrations.AlterField(
            model_name='teammemberprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='https://lpc-static-files-2024.s3.amazonaws.com/media/profile_pics/castolo.png', upload_to='profile_pics/'),
        ),
    ]
